language: ruby
rvm:
  - ruby-1.8.7
  - ruby-1.9.3
  - ruby-2.0.0
  - ruby-2.1
  - ruby-2.2
  - ruby-2.3
  - ruby-head
  - rbx-1
  - rbx-2.71828182
  - rbx-3.30
  - jruby-1.7
  - jruby-9.1.0.0
  - jruby-head
  - topaz
install:
  - gem install benchmark-ips || echo skipping benchmark-ips
  - gem install parser || echo skipping parser
  - gem install unparser || echo skipping unparser
env:
  - BACKEND=simple
  - BACKEND=bm
  - BACKEND=bmbm
  - BACKEND=bips
script: tests/tests.rb --$BACKEND
