language: ruby
rvm:
  - ruby-1.8.7-p371
  - ruby-1.9.3-p547
  - ruby-2.0.0-p648
  - ruby-2.1.10
  - ruby-2.2.5
  - ruby-2.3.1
  - ruby-head
  - jruby-1.7.25
  - jruby-9.0.5.0
  - jruby-9.1.0.0
  - jruby-head
  - rbx-2.71828182
  - rbx-3.29
install:
  - gem install benchmark-ips || echo skipping benchmark-ips
  - gem install parser || echo skipping parser
  - gem install unparser || echo skipping unparser
env:
  - BACKEND=simple
  - BACKEND=bm
  - BACKEND=bmbm
  - BACKEND=bips
script: tests/tests.rb --$BACKEND
matrix:
  include:
    - rvm: topaz
      install:
        - curl -Ol https://s3.amazonaws.com/jruby.org/downloads/9.1.0.0/jruby-bin-9.1.0.0.tar.gz
        - tar -zxf jruby-bin-9.1.0.0.tar.gz
      env: BACKEND=simple
      script: SQUASH_RUBY=jruby-9.1.0.0/bin/jruby tests/tests.rb --$BACKEND
